### PR TITLE
Grammar without "LINE"-Keyword

### PR DESCRIPTION
**Pull request by LHommeDeBat**
- Correct comment position is now calculated with the help of the "diff_hunk" string returned by the Github-API
- Grammar changed to work without the LINE keyword
Example: "BOT ADD ANNOTATION Override LINE 14" is now "BOT ADD ANNOTATION Override" (comment needs to be placed at specific line inside the changed code snippet)
- Fixed EOF (End of File) with the Grammar
- Adjusted GrammarService tests (For now commented out the line-checking) -> TODO: Somehow check lines

### CODE REVIEW

**Comment by MarvinWyrich** [comment]
Very nice improvement! It is okay to commit failing test cases. This ensures that you do not accidentally merge at the end before the test cases have passed or the code has been modified. 
I'll take a look at the test cases.

**Comment by MarvinWyrich** [comment]
I think that the method (at least if it stays in the current class) should not be public. Since diff hunks are something git-specific (and not GitHub-specific), we might consider moving the method to a more general class and offering it to the public (so that GitLabObjectTranslater and other file hosters can access it later, too). Simplifies testing as well.

**Comment by LHommeDeBat** [comment]
> I think that the method (at least if it stays in the current class) should not be public. Since diff hunks are something git-specific (and not GitHub-specific), we might consider moving the method to a more general class and offering it to the public (so that GitLabObjectTranslater and other file hosters can access it later, too). Simplifies testing as well.

We could maybe move the diff_hunk translation method to the "GitService" class.

**Comment by MarvinWyrich** [comment]
Okay, fine. I will review the actual code of the method later. Apart from that, I don't have any comments on this at the moment.

**Pull request merged**
